apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  CLOUDFLARE_AUTH_EMAIL: {{ .Values.secret.data.CLOUDFLARE_AUTH_EMAIL | b64enc | quote }}
  CLOUDFLARE_AUTH_KEY: {{ .Values.secret.data.CLOUDFLARE_AUTH_KEY | b64enc | quote }}

