apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-dns-updater
  namespace: cloudflare-dns
spec:
  successfulJobsHistoryLimit: 10  # Store only the last 10 successful jobs
  failedJobsHistoryLimit: 10      # Store only the last 10 failed jobs
  schedule: "0 * * * *"  # This schedule runs the job every hour
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cloudflare-dns-updater
        spec:
          containers:
          - name: cloudflare-dns-updater
            image: registry.apps.aizuddinzali.com:5000/cloudflare-dns-update/rust-updater:latest
            env:
            - name: CLOUDFLARE_API_URL
              value: "https://api.cloudflare.com/client/v4/zones/f1ed32ad43ea28a3cfdfa4a3da10c9f6/dns_records/512399a7512c61ee627ee334a9793713"
            - name: CLOUDFLARE_DNS_NAME
              value: "www.aizuddinzali.com"
            - name: CLOUDFLARE_AUTH_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secrets
                  key: CLOUDFLARE_AUTH_EMAIL
            - name: CLOUDFLARE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secrets
                  key: CLOUDFLARE_AUTH_KEY
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: registry-secret
